// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T3Theme
{
    internal sealed partial class Vsix
    {
        public const string Id = "T3Theme.a13c9cf2-023c-4ca5-b666-3aac5c98c5af";
        public const string Name = "T3 Theme";
        public const string Description = @"";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Dante Sparrås";
        public const string Tags = "theme";
        public const bool IsPreview = false;
    }
}
